# Generated by Django 5.1.4 on 2024-12-12 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='registered_user',
            new_name='registered_users',
        ),
    ]
