# Generated by Django 5.1.4 on 2024-12-11 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='organaizer',
            new_name='organizer',
        ),
    ]
