# Generated by Django 5.1.4 on 2024-12-12 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_registered_user_alter_event_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table=None,
        ),
    ]
