# Generated by Django 5.1.4 on 2024-12-12 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='events',
        ),
    ]
